name: cbf-cosine-warmup
version: v1

seed_everything: 42

trainer:
  accelerator: auto
  precision: 16-mixed
  max_epochs: 40
  deterministic: true
  num_sanity_val_steps: 0
  enable_progress_bar: true

model:
  class_path: CBFModel
  init_args:
    top_k: 50
    negative_sampling: true
    softmax_temperature: 0.05
    bias_correction: false
    mean_loss: true
    num_hidden_layers: 1
    last_hidden_units: 256
    item_dropout_prob: 0.0
    normalize_outputs: true
    optimizer_params:
      optimizer: adamw
      lr: 0.001
      weight_decay: 0.001
      lr_scheduler: cosine
      lr_scheduler_warmup_epochs: 5
      lr_scheduler_eta_min: 0.00001

data:
  class_path: CBFDataModule
  init_args:
    raw_dataset_root: /home/jeongmindo/projects/ably/data/bert/interaction
    pretrained_root: /home/jeongmindo/projects/ably/data/pretrained_text
    sql_dataset_root: /home/jeongmindo/projects/ably/data/sql
    model_path: /home/jeongmindo/projects/ably/data/output/cbf
    goods_filename: /home/jeongmindo/projects/ably/data/sql/goods.csv
    category_filename: /home/jeongmindo/projects/ably/data/sql/category.csv
    standard_category_filename: /home/jeongmindo/projects/ably/data/sql/standard_category.csv
    user_filename: /home/jeongmindo/projects/ably/data/sql/member.csv
    min_actions_per_user: 50
    max_items: 1000000
    batch_size: 128
    test_batch_size: 128
    max_len: 200
    num_workers: 0
    drop_last_batch: true
    item_embed_size: 256
    item_vocabulary_size: 120000
    use_age_info: true
    use_in_house_text_embed: true
    use_item_emb_in_item_tower: false
    use_attr: false
    market_embed_size: 128
    category_embed_size: 128
    price_group_embed_size: 0
    negative_sampling: true
    bias_correction: false
    max_test_samples: 200000
    num_test_samples_per_user: 10
    dataloader_random_seed: 0.0
    save_preprocessed_data: false

early_stopping:
  monitor: val/NDCG_50
  patience: 20
  mode: max

model_ckpt:
  monitor: val/NDCG_50
  mode: max
  filename: "best_acc_model"
  auto_insert_metric_name: false
  save_weights_only: true
  save_top_k: 1
