name: complementary_v2
version: v1
seed_everything: 42

trainer:
  accelerator: auto
  precision: 16-mixed
  max_epochs: 10
  deterministic: true
  callbacks:
    - class_path: WandbAlert
      init_args:
        monitor: ${model_ckpt.monitor}
        mode: ${model_ckpt.mode}

model:
  class_path: ComplementaryV2Model
  init_args:
    net:
      class_path: nets.complementary_v2.DCNv2
      init_args:
        input_dim: 16
        num_items: 750000
        num_categories: 1024
        num_cross_layers: 5
        deep_hidden_dims:
          - 512
          - 128
          - 64
          - 16
        item_embedding_dim: 512
        category_embedding_dim: 8
        dropout: 0.5
    lr: 0.0005

data:
  class_path: ComplementaryV2DataModule
  init_args:
    data_dir: /home/jeongmindo/projects/data/complementary_v2/train_data/click_n_purchase_3m
    goods_path: /home/jeongmindo/projects/data/sql/goods.csv
    goods_df_path: /home/jeongmindo/projects/data/complementary_v2/output/goods_df.pkl
    zscore_path: /home/jeongmindo/projects/data/complementary_v2/output/zscore.json
    batch_size: 20000
    num_workers: 16
    seed: 42

early_stopping:
  monitor: val/pr_auc
  patience: 5
  mode: max

model_ckpt:
  monitor: val/pr_auc
  mode: max
  filename: "best-ep={epoch:02d}-pr_auc={val/pr_auc:.4f}"
  auto_insert_metric_name: false
